export const images = [
    { src: "/images/0.png", title: "scrambled it to make a type specimen book" },
    { src: "/images/1.png", title: "now use Lorem Ipsum as their default model text" },
    { src: "/images/2.png", title: "Various versions have evolved over the years" },
    { src: "/images/3.png", title: "Lorem Ipsum available" },
    { src: "/images/4.png", title: "you need to be sure there" },
    { src: "/images/5.png", title: "making this the first true generator on the Internet" },
    { src: "/images/3.png", title: "look even slightly believable" },
    { src: "/images/2.png", title: "Various versions have evolved" },
    { src: "/images/4.png", title: "Ipsum as their default model tex" },
    { src: "/images/0.png", title: "scrambled it to make a type" },
    { src: "/images/5.png", title: "making this the first true" },
    { src: "/images/1.png", title: "Various versions have evolved" },
    { src: "/images/3.png", title: "making this the first true" },
    { src: "/images/0.png", title: "scrambled it to make a type" },
    { src: "/images/1.png", title: "Various versions have evolved" },
    { src: "/images/2.png", title: "Ipsum as their default model tex" },
    { src: "/images/4.png", title: "making this the first true" },
    { src: "/images/5.png", title: "scrambled it to make a type" },
]
